name: ethio_numbers
description: "this package used to convert Arabic number to Amharic, Afaan Oromo or Tigrigna text upto decillion (10^33) number."
version: 0.0.4
repository: https://github.com/Melloss/ethio_numbers

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


